application: formaltranslate
version: 0.01
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: main.app

- url: /rest
  script: rest_requests.app

- url: /api
  script: api_client_requests.app

libraries:
- name: webapp2
  version: "2.5.2"
